export const dummyData =[
    {
      "id": 1,
      "jobTitle": "Software Engineer",
      "companyName": "Google",
      "location": "San Francisco",
      "jobDescription": "Develop cutting-edge software solutions...",
      "jobType": "Full-Time",
      "applicationLink": "https://careers.google.com/jobs/results/12345-software-engineer/",
      "postedDate": "2024-09-10",
      "companyLogo": "https://logo.clearbit.com/google.com"
    },
    {
      "id": 2,
      "jobTitle": "Frontend Developer",
      "companyName": "Facebook",
      "location": "New York",
      "jobDescription": "Build user-friendly web applications...",
      "jobType": "Contract",
      "applicationLink": "https://www.facebook.com/careers/98765-frontend-developer/",
      "postedDate": "2024-09-08",
      "companyLogo": "https://logo.clearbit.com/facebook.com"
    },
    {
      "id": 3,
      "jobTitle": "Backend Developer",
      "companyName": "Amazon",
      "location": "Seattle",
      "jobDescription": "Design and maintain backend services...",
      "jobType": "Full-Time",
      "applicationLink": "https://amazon.jobs/en/jobs/23456-backend-developer/",
      "postedDate": "2024-09-12",
      "companyLogo": "https://logo.clearbit.com/amazon.com"
    },
    {
      "id": 4,
      "jobTitle": "Data Scientist",
      "companyName": "Netflix",
      "location": "Los Angeles",
      "jobDescription": "Analyze data to improve recommendation algorithms...",
      "jobType": "Full-Time",
      "applicationLink": "https://jobs.netflix.com/positions/34567-data-scientist/",
      "postedDate": "2024-09-11",
      "companyLogo": "https://logo.clearbit.com/netflix.com"
    },
    {
      "id": 5,
      "jobTitle": "UI/UX Designer",
      "companyName": "Apple",
      "location": "Cupertino",
      "jobDescription": "Design visually appealing and user-friendly interfaces...",
      "jobType": "Full-Time",
      "applicationLink": "https://jobs.apple.com/en-us/details/45678-ui-ux-designer/",
      "postedDate": "2024-09-09",
      "companyLogo": "https://logo.clearbit.com/apple.com"
    },
    {
      "id": 6,
      "jobTitle": "DevOps Engineer",
      "companyName": "Microsoft",
      "location": "Redmond",
      "jobDescription": "Implement CI/CD pipelines and automate workflows...",
      "jobType": "Full-Time",
      "applicationLink": "https://careers.microsoft.com/us/en/job/56789-devops-engineer/",
      "postedDate": "2024-09-05",
      "companyLogo": "https://logo.clearbit.com/microsoft.com"
    },
    {
      "id": 7,
      "jobTitle": "Full Stack Developer",
      "companyName": "Spotify",
      "location": "Remote",
      "jobDescription": "Develop and manage front and back-end systems...",
      "jobType": "Part-Time",
      "applicationLink": "https://www.spotifyjobs.com/jobs/67890-full-stack-developer/",
      "postedDate": "2024-09-07",
      "companyLogo": "https://logo.clearbit.com/spotify.com"
    },
    {
      "id": 8,
      "jobTitle": "Machine Learning Engineer",
      "companyName": "Tesla",
      "location": "Palo Alto",
      "jobDescription": "Build and deploy machine learning models...",
      "jobType": "Full-Time",
      "applicationLink": "https://www.tesla.com/careers/job/78901-ml-engineer/",
      "postedDate": "2024-09-04",
      "companyLogo": "https://logo.clearbit.com/tesla.com"
    },
    {
      "id": 9,
      "jobTitle": "Security Analyst",
      "companyName": "Cisco",
      "location": "San Jose",
      "jobDescription": "Monitor and secure company networks...",
      "jobType": "Full-Time",
      "applicationLink": "https://jobs.cisco.com/jobs/89123-security-analyst/",
      "postedDate": "2024-09-06",
      "companyLogo": "https://logo.clearbit.com/cisco.com"
    },
    {
      "id": 10,
      "jobTitle": "Cloud Engineer",
      "companyName": "Oracle",
      "location": "Austin",
      "jobDescription": "Manage cloud infrastructure and services...",
      "jobType": "Contract",
      "applicationLink": "https://oracle.taleo.net/jobs/01234-cloud-engineer/",
      "postedDate": "2024-09-08",
      "companyLogo": "https://logo.clearbit.com/oracle.com"
    },
    {
      "id": 11,
      "jobTitle": "Product Manager",
      "companyName": "Twitter",
      "location": "San Francisco",
      "jobDescription": "Lead product development initiatives...",
      "jobType": "Full-Time",
      "applicationLink": "https://careers.twitter.com/job/01234-product-manager/",
      "postedDate": "2024-09-03",
      "companyLogo": "https://logo.clearbit.com/twitter.com"
    },
    {
      "id": 12,
      "jobTitle": "Network Engineer",
      "companyName": "AT&T",
      "location": "Dallas",
      "jobDescription": "Design and optimize network infrastructure...",
      "jobType": "Full-Time",
      "applicationLink": "https://att.jobs/network-engineer/56789/",
      "postedDate": "2024-09-01",
      "companyLogo": "https://logo.clearbit.com/att.com"
    },
    {
      "id": 13,
      "jobTitle": "Software Architect",
      "companyName": "IBM",
      "location": "Boston",
      "jobDescription": "Lead the design of complex software systems...",
      "jobType": "Full-Time",
      "applicationLink": "https://ibm.com/careers/01234-software-architect/",
      "postedDate": "2024-09-02",
      "companyLogo": "https://logo.clearbit.com/ibm.com"
    },
    {
      "id": 14,
      "jobTitle": "Blockchain Developer",
      "companyName": "Coinbase",
      "location": "Remote",
      "jobDescription": "Develop blockchain applications and smart contracts...",
      "jobType": "Contract",
      "applicationLink": "https://coinbase.com/careers/blockchain-developer/12345/",
      "postedDate": "2024-09-11",
      "companyLogo": "https://logo.clearbit.com/coinbase.com"
    },
    {
      "id": 15,
      "jobTitle": "Database Administrator",
      "companyName": "Oracle",
      "location": "Austin",
      "jobDescription": "Manage and optimize databases for performance...",
      "jobType": "Full-Time",
      "applicationLink": "https://oracle.taleo.net/jobs/67890-database-admin/",
      "postedDate": "2024-09-09",
      "companyLogo": "https://logo.clearbit.com/oracle.com"
    },
    {
      "id": 16,
      "jobTitle": "AI Researcher",
      "companyName": "OpenAI",
      "location": "San Francisco",
      "jobDescription": "Conduct research in artificial intelligence and machine learning...",
      "jobType": "Full-Time",
      "applicationLink": "https://openai.com/careers/ai-researcher/",
      "postedDate": "2024-09-12",
      "companyLogo": "https://logo.clearbit.com/openai.com"
    },
    {
      "id": 17,
      "jobTitle": "Content Writer",
      "companyName": "Medium",
      "location": "Remote",
      "jobDescription": "Create high-quality content for the platform...",
      "jobType": "Part-Time",
      "applicationLink": "https://medium.com/careers/content-writer/",
      "postedDate": "2024-09-07",
      "companyLogo": "https://logo.clearbit.com/medium.com"
    },
    {
      "id": 18,
      "jobTitle": "Game Developer",
      "companyName": "Epic Games",
      "location": "Cary",
      "jobDescription": "Develop and optimize game features and mechanics...",
      "jobType": "Full-Time",
      "applicationLink": "https://epicgames.com/careers/game-developer/",
      "postedDate": "2024-09-05",
      "companyLogo": "https://logo.clearbit.com/epicgames.com"
    },
    {
      "id": 19,
      "jobTitle": "Graphic Designer",
      "companyName": "Adobe",
      "location": "San Jose",
      "jobDescription": "Create engaging visual content for marketing...",
      "jobType": "Contract",
      "applicationLink": "https://adobe.com/careers/graphic-designer/",
      "postedDate": "2024-09-06",
      "companyLogo": "https://logo.clearbit.com/adobe.com"
    },
    {
      "id": 20,
      "jobTitle": "Technical Support Specialist",
      "companyName": "Zoom",
      "location": "Remote",
      "jobDescription": "Provide technical support to users...",
      "jobType": "Full-Time",
      "applicationLink": "https://zoom.us/careers/tech-support-specialist/",
      "postedDate": "2024-09-04",
      "companyLogo": "https://logo.clearbit.com/zoom.us"
    },
    {
      "id": 21,
      "jobTitle": "Project Manager",
      "companyName": "Asana",
      "location": "San Francisco",
      "jobDescription": "Lead project planning and execution...",
      "jobType": "Full-Time",
      "applicationLink": "https://asana.com/careers/project-manager/",
      "postedDate": "2024-09-13",
      "companyLogo": "https://logo.clearbit.com/asana.com"
    },
    {
      "id": 22,
      "jobTitle": "Business Analyst",
      "companyName": "Deloitte",
      "location": "Chicago",
      "jobDescription": "Analyze business processes and provide data-driven insights...",
      "jobType": "Full-Time",
      "applicationLink": "https://deloitte.com/careers/business-analyst/",
      "postedDate": "2024-09-10",
      "companyLogo": "https://logo.clearbit.com/deloitte.com"
    },
    {
      "id": 23,
      "jobTitle": "Mobile App Developer",
      "companyName": "Snapchat",
      "location": "Venice",
      "jobDescription": "Develop and maintain mobile applications for iOS and Android...",
      "jobType": "Contract",
      "applicationLink": "https://snapchat.com/careers/mobile-developer/",
      "postedDate": "2024-09-02",
      "companyLogo": "https://logo.clearbit.com/snapchat.com"
    },
    {
      "id": 24,
      "jobTitle": "Cybersecurity Specialist",
      "companyName": "Symantec",
      "location": "San Diego",
      "jobDescription": "Protect systems and data from cyber threats...",
      "jobType": "Full-Time",
      "applicationLink": "https://symantec.com/careers/cybersecurity-specialist/",
      "postedDate": "2024-09-06",
      "companyLogo": "https://logo.clearbit.com/symantec.com"
    },
    {
      "id": 25,
      "jobTitle": "IT Consultant",
      "companyName": "Accenture",
      "location": "London",
      "jobDescription": "Provide technology consulting services...",
      "jobType": "Full-Time",
      "applicationLink": "https://accenture.com/careers/it-consultant/",
      "postedDate": "2024-09-08",
      "companyLogo": "https://logo.clearbit.com/accenture.com"
    },
    {
      "id": 26,
      "jobTitle": "Marketing Specialist",
      "companyName": "HubSpot",
      "location": "Boston",
      "jobDescription": "Develop and execute marketing campaigns...",
      "jobType": "Part-Time",
      "applicationLink": "https://hubspot.com/careers/marketing-specialist/",
      "postedDate": "2024-09-03",
      "companyLogo": "https://logo.clearbit.com/hubspot.com"
    },
    {
      "id": 27,
      "jobTitle": "QA Engineer",
      "companyName": "Dropbox",
      "location": "Remote",
      "jobDescription": "Test and ensure the quality of software products...",
      "jobType": "Full-Time",
      "applicationLink": "https://dropbox.com/careers/qa-engineer/",
      "postedDate": "2024-09-11",
      "companyLogo": "https://logo.clearbit.com/dropbox.com"
    },
    {
      "id": 28,
      "jobTitle": "Technical Writer",
      "companyName": "GitHub",
      "location": "Remote",
      "jobDescription": "Write clear and concise technical documentation...",
      "jobType": "Contract",
      "applicationLink": "https://github.com/careers/technical-writer/",
      "postedDate": "2024-09-05",
      "companyLogo": "https://logo.clearbit.com/github.com"
    },
    {
      "id": 29,
      "jobTitle": "Solutions Architect",
      "companyName": "Salesforce",
      "location": "San Francisco",
      "jobDescription": "Design scalable software solutions...",
      "jobType": "Full-Time",
      "applicationLink": "https://salesforce.com/careers/solutions-architect/",
      "postedDate": "2024-09-10",
      "companyLogo": "https://logo.clearbit.com/salesforce.com"
    },
    {
      "id": 30,
      "jobTitle": "SEO Specialist",
      "companyName": "Moz",
      "location": "Seattle",
      "jobDescription": "Optimize website content for search engines...",
      "jobType": "Part-Time",
      "applicationLink": "https://moz.com/careers/seo-specialist/",
      "postedDate": "2024-09-08",
      "companyLogo": "https://logo.clearbit.com/moz.com"
    }
  ]
  